## Install flex-table-card from here https://github.com/custom-cards/flex-table-card
resources:
  - url: /local/flex-table-card/flex-table-card.js
    type: js

views:
  - title: ESXi Stats Example
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:flex-table-card
            title: ESXi Hosts
            clickable: true
            entities:
              include: sensor.esxi_vmhost*
            columns:
              - name: Name
                data: name
              - name: Version
                data: version
              - name: Uptime (H)
                data: uptime_hours
              - name: CPU Use (GHz)
                data: cpuusage_ghz
              - name: Mem Use (GB)
                data: memusage_gb
              - name: VMs
                data: vms
          - type: custom:flex-table-card
            title: ESXi Virtual Machines
            clickable: true
            entities:
              include: sensor.esxi_vm_*
            columns:
              - name: Name
                data: name
              - name: Status
                data: status
              - name: State
                data: state
              - name: Uptime (H)
                data: uptime_hours
              - name: CPU Usage (%)
                data: cpu_use_pct
              - name: CPUs
                data: cpu_count
              - name: Mem Use (MB)
                data: memory_used_mb
              - name: Mem Total (MB)
                data: memory_allocated_mb
              - name: Storage Used (GB)
                data: used_space_gb
              - name: VM Tools
                data: tools_status
              - name: Snapshots
                data: snapshots
          - type: custom:flex-table-card
            title: ESXi Datastores
            clickable: true
            entities:
              include: sensor.esxi_datastore*
            columns:
              - name: Name
                data: name
              - name: Free Space (GB)
                data: free_space_gb
              - name: Capacity (GB)
                data: total_space_gb
              - name: Hosts
                data: connected_hosts
              - name: VMs
                data: virtual_machines
              - name: Type
                data: type
